version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    container_name: booking_postgres
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME_DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    restart: unless-stopped

volumes:
  postgres_data:
